# Generated by Django 4.0.1 on 2022-01-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_tag_remove_bookmark_tags_bookmark_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
